name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
        default: 'dev'
      REGISTRY:
        required: true
        type: string
        default: '368076259134.dkr.ecr.us-east-1.amazonaws.com'
      REPOSITORY:
        required: true
        type: string
        default:  'sdk-example'
      IMAGE_TAG:
        required: true
        type: string
        default:  'sdk-example'
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::368076259134:role/github-actions-role
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR          
        run: |
          docker build -t ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ inputs.IMAGE_TAG }} .
          docker push ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ inputs.IMAGE_TAG }}
          
      - name: Publish
        run: |
          aws ecs update-service --service ${{ inputs.IMAGE_TAG }}-svc --force-new-deployment --cluster SDK-Example-CLS
